name: Notify CICD (frontend)

on:
  push:
    branches: [development, main]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch to CICD repo
        env:
          CICD_OWNER: eli-pavlov
          CICD_REPO: cicd-newsapp
          GH_PAT: ${{ secrets.CICD_REPO_PAT }}
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          SHORT_SHA=$(echo "$COMMIT_SHA" | cut -c1-7)
          jq -n \
            --arg branch "$BRANCH_NAME" \
            --arg commit_message "$COMMIT_MESSAGE" \
            --arg commit_sha "$COMMIT_SHA" \
            --arg short_sha "$SHORT_SHA" \
            '{
              event_type:"frontend",
              client_payload:{
                originator:"frontend",
                branch:$branch,
                commit_message:$commit_message,
                commit_sha:$commit_sha,
                short_sha:$short_sha
              }
            }' > body.json

          curl -sSL -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_PAT}" \
            https://api.github.com/repos/${CICD_OWNER}/${CICD_REPO}/dispatches \
            -d @body.json
