name: Notify CICD (Frontend)

on:
  push:
    branches: [development, main]

permissions:
  contents: read

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Guard required secrets
        shell: bash
        run: |
          if [ -z "${{ secrets.CICD_REPO_PAT }}" ]; then
            echo "::error::Missing CICD_REPO_PAT secret. This secret needs repo scope on the cicd-newsapp repository."
            exit 1
          fi

      - name: Ensure jq is available
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Send repository_dispatch to CICD repo
        env:
          # The target repository that will RECEIVE the event
          CICD_OWNER: eli-pavlov
          CICD_REPO: cicd-newsapp
          GH_PAT: ${{ secrets.CICD_REPO_PAT }}
          # The source repository context that TRIGGERED the event
          SOURCE_REPO: ${{ github.repository }}
          SOURCE_REF:  ${{ github.ref_name }}  # branch/tag name (not SHA)
          SOURCE_SHA:  ${{ github.sha }}       # commit SHA (extra context)
        run: |
          set -euo pipefail
          echo "Dispatching event to ${CICD_OWNER}/${CICD_REPO} for ${SOURCE_REPO}@${SOURCE_REF} (${SOURCE_SHA})"

          jq -n \
            --arg repo "$SOURCE_REPO" \
            --arg ref  "$SOURCE_REF" \
            --arg sha  "$SOURCE_SHA" \
            '{
              "event_type": "frontend",
              "client_payload": {
                "source_repo": $repo,
                "source_ref":  $ref,
                "source_sha":  $sha
              }
            }' > body.json

          HTTP=$(
            curl -fsSL -o /dev/null -w "%{http_code}" -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GH_PAT}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/${CICD_OWNER}/${CICD_REPO}/dispatches" \
              -d @body.json || true
          )
          if [ "$HTTP" != "204" ]; then
            echo "::error::repository_dispatch failed with HTTP ${HTTP}"
            echo "Payload:"; cat body.json
            exit 1
          fi
          echo "✅ repository_dispatch accepted (204)."
